name: CI-CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: .
      VERSION: 1.${{ github.run_number }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: python -m pytest test/

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/quote-app:${{ env.VERSION }} .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/quote-app:${{ env.VERSION }}

      - name: (Optional) Tag 'latest'
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/quote-app:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/quote-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/quote-app:latest
